on:
  push:
    branches:
      - test-deploy
name: Deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: '2.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn
    - name: Install serverless
      run: npm install -g serverless
    - name: serverless deploy
      run: sls deploy --stage 'staging' --db_pass '${{ secrets.STAGING_DB_PASS }}' --fb_secret '${{ secrets.STAGING_FB_SECRET }}' --jwt_secret '${{ secrets.STAGING_JWT_SECRET }}'  --gcm_api_key '${{ secrets.STAGING_GCM_API_KEY }}' --vapid_priv_key '${{ secrets.STAGING_VAPID_PRIV_KEY }}' --aes_key '${{ secrets.STAGING_AES_KEY }}'  --aws_sns_secret '${{ secrets.STAGING_AWS_SNS_SECRET }}' --aws_sns_topicarn '${{ secrets.STAGING_AWS_SNS_TOPICARN }}' --google_secret '${{ secrets.STAGING_GOOGLE_SECRET }}'  --aws_s3_secret '${{ secrets.STAGING_AWS_S3_SECRET }}' 
      env:
        AWS_REGION: eu-west-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_EXECUTION_ENV: staging
        DB_HOST: staging.db.covidografia.pt
        DB_USER: postgres
        DB_PASS: ${{ secrets.STAGING_DB_PASS }}
        DB_NAME: postgres
        DB_PORT: "54320"
        CORS_ORIGIN: https://staging.app.covidografia.pt
        FB_APP_ID: 142877133789647
        FB_APP_SECRET: ${{ secrets.STAGING_FB_SECRET }}
        FB_APP_SCOPE: email,public_profile
        FB_CALLBACK_URL: https://staging.api.covidografia.pt/api/v1
        FB_USER_INFO_URL: https://graph.facebook.com/v3.0/me?fields=id,name,email
        GOOGLE_APP_ID: 521794831407-kgvjkksomko9rg6um8i7s076l0a9ltjh.apps.googleusercontent.com
        GOOGLE_APP_SECRET: ${{ secrets.STAGING_GOOGLE_SECRET }}
        GOOGLE_APP_SCOPE: profile email openid
        GOOGLE_CALLBACK_URL: https://staging.api.covidografia.pt/api/v1
        GOOGLE_USER_INFO_URL: https://www.googleapis.com/oauth2/v1/userinfo
        AFTER_LOGIN_CALLBACK_URL: https://staging.app.covidografia.pt
        JWT_SECRET: ${{ secrets.STAGING_JWT_SECRET }}
        HOME_URL: https://www.covidografia.pt
        GCM_API_KEY: ${{ secrets.STAGING_GCM_API_KEY }}
        VAPID_PRIVATE_KEY: ${{ secrets.STAGING_VAPID_PRIV_KEY }}
        VAPID_PUBLIC_KEY: BA5Tr13lfJCBPb9ZaXlTKUetDORnHROGI_S7cumwdDR9f-ZxYI-4Y2OvIC4WgZxcanE9znpKufP6wLA5kdIG2Ak
        VAPID_SUBJECT: https://staging.app.covidografia.pt
        AES_256_KEY: ${{ secrets.STAGING_AES_KEY }}
        PRODUCTION: 0
        AWS_REGION_SNS: eu-west-1
        AWS_SNS_ACCESS_KEY_ID: AKIA3PHZAWHE536M366R
        AWS_SNS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SNS_SECRET }}
        AWS_SNS_TOPICARN: ${{ secrets.STAGING_AWS_SNS_TOPICARN }}
        AWS_REGION_S3: eu-west-1
        AWS_S3_ACCESS_KEY_ID: AKIA3PHZAWHE454DOOR2
        AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_S3_SECRET }}
        AWS_S3_BUCKET: covidografia-share-dashboard
        AWS_S3_DOMAIN: https://staging.static.covidografia.pt 
  